version: "2.2"

services:
  data_db:
    image: postgres:14.7
    container_name: "db.points.skelmis.co.nz"
    restart: always
    command: -p 2301
    ports:
      - "2301:2301"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: points_skelmis_co_nz
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: product-defeat-follow-worshiper-swimwear-drown
    volumes:
      - .db:/var/lib/postgresql/data
  data_web:
    image: ghcr.io/skelmis/points.skelmis.co.nz:master
    container_name: "web_points.skelmis.co.nz"
    restart: always
    ports:
      - "2300:2300"
    depends_on:
      - data_db
    cpus: 1
    mem_limit: 1g
    mem_reservation: 256m
    environment:
      SERVING_DOMAIN: "points.skelmis.co.nz"
      POSTGRES_HOST: db.points.skelmis.co.nz
      POSTGRES_DB: its_a_db_woo
      POSTGRES_USER: its_a_db_woo_user
      POSTGRES_PASSWORD: its_a_db_woo_password_for_db_user
      POSTGRES_PORT: 2301

#networks:
#  default:
#    name: spook
#    external: true